---
title: "Tips for writing a NSF GRFP"
author: "Mark Scheuerell"
date: "21 September 2022"
output:
  ioslides_presentation:
    css: lecture_slides.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Who am I?

* Assistant Unit Leader, USGS Washington Cooperative Fish and Wildlife Research Unit

* Associate Professor, School of Aquatic and Fishery Sciences


## Why am I here?

* Associate Editor, _Ecological Research_ (2007-2017)

* Associate Editor, _Limnology and Oceanography Letters_ (2016-present)

* Former panel member, NSF GRFP program


# Proposal elements


## 2 primary pieces

1. Personal background & Future goals

2. Research plan


## Personal background & future goals | 3 elements

1. Personal development plan and career goals

2. Intellectual merit

3. Broader impacts


## Personal background & future goals | Tell a story

* Reviewers are busy, tired & looking for entertainment

> - Consider these opening statements

> - "I fell in love with the ocean when I was 10 years old..."

> - "The sand was hot, the air reeked of rotting kelp, and I was in love..."


## Personal background & future goals | Tell a story

* Help the reviewers relate to **you**


## Personal background & future goals | It's about you

* Why **you** have the _intellectual merit_ to take on your proposed project

* What _broader impacts_ **you** will have on the world


# Research statement


## Research statement | Objectives

Consider a two-step approach

1. "The overall goal of this study is to..."  

2. "Specifically, I will test the following two hypotheses..."


## Research statement | Objectives

* Begin with general questions

> - End with specific hypotheses/predictions

> - Avoid statements like "will be different" or "will show a pattern"


## Research statement | Materials & methods

* Use enough detail that a reviewer could envision it accurately

> - Provide important details & omit irrelevant ones

> - Sub-headings can be a useful way to organize the section (eg, "Field study", "Data analysis")


## Research statement | Intellectual merit

* Should describe how the proposed work will advance our knowledge

> - Should be about **the science** versus **you**


## Research statement | Broader impacts

* Should strengthen the relationship between the science community and society

> - This is an increasingly important aspect of grant proposals


## Broader Impacts | Evaluation criteria

What is the potential for the proposed activity to benefit society or advance desired societal outcomes?

> - Match your strategy to the target community

> - For example, if you are planning for outreach at elementary schools, you will need to package your research into products children can understand


## Broader Impacts | Evaluation criteria

To what extent do the proposed activities suggest and explore creative, original or potentially transformative concepts?

> - Describe how you will expand on known, effective strategies and give examples of successful ones

> - For example, hands-on, project-based learning enhances student performance, increases motivation and engagement, and develops critical thinking


## Broader Impacts | Evaluation criteria

Is the plan for carrying out the proposed activities well-reasoned, well-organized and based on sound rationale?

> - Develop your Broader Impacts plan in the same way you develop the rationale for your research activities, including an evaluation plan

> - For example, how will you gauge the success of engaging an elementary school audience?


## Broader Impacts | Evaluation criteria

How well qualified is the individual (institution) to conduct the proposed activities?

> - Play to your strengths

> - For example, if you have a talent for creating games, perhaps you could create a game about a food web that exemplifies your research on the interaction of different fish species.

> - Think outside the box


# Other thoughts


## Plan ahead

* Read the instructions

> - Read them again

> - Give letter writers adequate notice & remind them


## Writing is hard

* Start early & get feedback

> - Markus and I worked over **9** drafts of his personal statement & **11* drafts of his research statement


## Feel proud

* Rejection is common, but know that you gave your best

> - Failed proposals are great fodder for future proposals



